python demo.py \
                --imagedir ~/bigfoot-FoMo/ijrr/2024-11-21/red_2024-11-21-10-34/ \
                --stereo \
                --disable_vis \
                --reconstruction_path "output" \
                --weights /home/mbo/legs_ws/src/droid_slam_ros/droid.pth \
                --trajectory_path "output/trajectory2.txt" \
                --buffer 6000 \
                --t0 0 \
                --stride 3 \
                --beta 0.3 \
                --filter_thresh 2.0 \
                --warmup 4 \
                --keyframe_thresh 4.0 \
                --frontend_thresh 16.0 \
                --frontend_window 50 \
                --frontend_radius 2 \
                --frontend_nms 1 \
                --backend_thresh 22.0 \
                --backend_radius 2 \
                --backend_nms 3